[workspace]
members = [ "examples/*", "pyreccaster","reccaster", "wire"]
default-members = ["pyreccaster", "reccaster", "wire"]
resolver = "2"

[workspace.lints.rust]
missing_docs = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
