[package]
name = "basic-reccaster"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "^0.1.41"
tracing-subscriber = "^0.3.18"
reccaster = { path = "../../reccaster"}
